export type Member = {
  id: string
  name: string
  email: string
  company: string
  organization1: string
  organization2: string
  organization3: string
  role: "Admin" | "Editor" | "Viewer" | "その他"
  status: "有効" | "廃止"
  registrationDate: string
  usageFunctions: string[]
}

export const sampleMembers: Member[] = [
  {
    id: "0000000020",
    name: "鈴木次郎",
    email: "suzuki@aeonmall.com",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "マーケティング部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-01-15",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000019",
    name: "高橋裕子",
    email: "takahashi@aeonmall.com",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "マーケティング部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-01-20",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000018",
    name: "中田由美",
    email: "nakatay@aeonmall.com",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "マーケティング部",
    organization3: "",
    role: "Viewer",
    status: "有効",
    registrationDate: "2024-02-01",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000017",
    name: "川口和夫",
    email: "kawaguchi@aeonmall.com",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "マーケティング部",
    organization3: "",
    role: "その他",
    status: "廃止",
    registrationDate: "2024-02-10",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000016",
    name: "石田剛",
    email: "ishidat@aeonmall.com",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "パートナーシップ部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-02-15",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000015",
    name: "木村正子",
    email: "kimuram@aeonmall.com",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "パートナーシップ部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-03-01",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000014",
    name: "佐々木一",
    email: "sasaki@opa.co.jp",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "アセット活用部",
    organization3: "",
    role: "Viewer",
    status: "有効",
    registrationDate: "2024-03-05",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000013",
    name: "田中花子",
    email: "tanaka@sample-corp.example",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "アセット活用部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-03-10",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000012",
    name: "佐藤太郎",
    email: "sato@sample-corp.example",
    company: "イオンモール",
    organization1: "営業統括部",
    organization2: "ESGグループ",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-03-15",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000011",
    name: "伊藤美咲",
    email: "ito@sample-corp.example",
    company: "イオンモール",
    organization1: "",
    organization2: "",
    organization3: "",
    role: "その他",
    status: "有効",
    registrationDate: "2024-03-20",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000030",
    name: "山田太郎",
    email: "yamada@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "マーケティング部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-01",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000029",
    name: "田村花子",
    email: "tamura@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "マーケティング部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-04-02",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000028",
    name: "佐藤次郎",
    email: "sato.jiro@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "パートナーシップ部",
    organization3: "",
    role: "Viewer",
    status: "有効",
    registrationDate: "2024-04-03",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000027",
    name: "鈴木美咲",
    email: "suzuki.misaki@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "パートナーシップ部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-04",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000026",
    name: "高橋一郎",
    email: "takahashi.ichiro@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "アセット活用部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-04-05",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000025",
    name: "中村由美",
    email: "nakamura.yumi@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "アセット活用部",
    organization3: "",
    role: "Viewer",
    status: "廃止",
    registrationDate: "2024-04-06",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000024",
    name: "伊藤健太",
    email: "ito.kenta@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "ESGグループ",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-07",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000023",
    name: "渡辺真理",
    email: "watanabe.mari@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "営業統括部",
    organization2: "ESGグループ",
    organization3: "",
    role: "その他",
    status: "有効",
    registrationDate: "2024-04-08",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000022",
    name: "小林正雄",
    email: "kobayashi.masao@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "技術開発部",
    organization2: "システム企画課",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-09",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000021",
    name: "加藤恵子",
    email: "kato.keiko@sample-corp.example",
    company: "サンプル株式会社",
    organization1: "技術開発部",
    organization2: "システム企画課",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-04-10",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000031",
    name: "松本和子",
    email: "matsumoto.kazuko@sample-corp.example",
    company: "イオンリテール",
    organization1: "東日本支社",
    organization2: "東北・北海道事業部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-11",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000032",
    name: "森田健一",
    email: "morita.kenichi@sample-corp.example",
    company: "イオンリテール",
    organization1: "東日本支社",
    organization2: "東北・北海道事業部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-04-12",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000033",
    name: "清水美香",
    email: "shimizu.mika@sample-corp.example",
    company: "イオンリテール",
    organization1: "東日本支社",
    organization2: "首都圏事業部",
    organization3: "",
    role: "Viewer",
    status: "有効",
    registrationDate: "2024-04-13",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000034",
    name: "橋本雄二",
    email: "hashimoto.yuji@sample-corp.example",
    company: "イオンフィナンシャルサービス",
    organization1: "西日本支社",
    organization2: "関西事業部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-14",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000035",
    name: "藤田智子",
    email: "fujita.tomoko@sample-corp.example",
    company: "イオンフィナンシャルサービス",
    organization1: "西日本支社",
    organization2: "関西事業部",
    organization3: "",
    role: "Editor",
    status: "廃止",
    registrationDate: "2024-04-15",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000036",
    name: "岡田修平",
    email: "okada.shuhei@sample-corp.example",
    company: "イオンモール",
    organization1: "西日本支社",
    organization2: "九州事業部",
    organization3: "",
    role: "Viewer",
    status: "有効",
    registrationDate: "2024-04-16",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000037",
    name: "長谷川恵",
    email: "hasegawa.megumi@sample-corp.example",
    company: "イオンモール",
    organization1: "西日本支社",
    organization2: "九州事業部",
    organization3: "",
    role: "Admin",
    status: "有効",
    registrationDate: "2024-04-17",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000038",
    name: "村上直樹",
    email: "murakami.naoki@sample-corp.example",
    company: "イオンリテール",
    organization1: "中部支社",
    organization2: "東海事業部",
    organization3: "",
    role: "Editor",
    status: "有効",
    registrationDate: "2024-04-18",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000039",
    name: "近藤由紀",
    email: "kondo.yuki@sample-corp.example",
    company: "イオンリテール",
    organization1: "中部支社",
    organization2: "東海事業部",
    organization3: "",
    role: "Viewer",
    status: "有効",
    registrationDate: "2024-04-19",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
  {
    id: "0000000040",
    name: "斎藤光男",
    email: "saito.mitsuo@sample-corp.example",
    company: "イオンフィナンシャルサービス",
    organization1: "中部支社",
    organization2: "北陸事業部",
    organization3: "",
    role: "その他",
    status: "有効",
    registrationDate: "2024-04-20",
    usageFunctions: ["施設情許管理", "会員管理"],
  },
]
